### ISSUE TITLE
TypeError: Cannot read property 'getScreenshot' of null

### ISSUE THREAD

**Issue by gigerbytes** [dashboardphilippines/react-webcam-barcode-scanner#2]
Sometimes receive this error when closing the component. screenshot below:
<img width="955" alt="Screen Shot 2020-05-17 at 03 36 14" src="https://user-images.githubusercontent.com/5770876/82128713-ae91f380-97ef-11ea-9ac8-02e58630fb24.png">

**Comment by phillytan** [comment]
Fixed!

**Comment by robbienicol** [comment]
> Fixed!

can you share how you did so? 
thanks !
